In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/IMDB

/content/drive/MyDrive/IMDB


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8140, 4354, 3318, 372],
 [8140, 4354, 3318, 5807],
 [8140, 4267, 3318, 9208],
 [8426, 3452, 2499, 980, 3575],
 [8426, 3452, 2499, 980, 5776],
 [9907, 8140, 3780, 3318, 488],
 [4238, 7581, 6720, 980]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8140 4354 3318  372]
 [   0    0    0    0 8140 4354 3318 5807]
 [   0    0    0    0 8140 4267 3318 9208]
 [   0    0    0 8426 3452 2499  980 3575]
 [   0    0    0 8426 3452 2499  980 5776]
 [   0    0    0 9907 8140 3780 3318  488]
 [   0    0    0    0 4238 7581 6720  980]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 574ms/step


array([[[-2.56885290e-02,  7.06331804e-03,  3.31770219e-02,
          4.86553945e-02, -1.53257139e-02, -1.48317590e-02,
          3.89952995e-02, -2.15779990e-04,  3.00152414e-02,
          1.65792592e-02],
        [-2.56885290e-02,  7.06331804e-03,  3.31770219e-02,
          4.86553945e-02, -1.53257139e-02, -1.48317590e-02,
          3.89952995e-02, -2.15779990e-04,  3.00152414e-02,
          1.65792592e-02],
        [-2.56885290e-02,  7.06331804e-03,  3.31770219e-02,
          4.86553945e-02, -1.53257139e-02, -1.48317590e-02,
          3.89952995e-02, -2.15779990e-04,  3.00152414e-02,
          1.65792592e-02],
        [-2.56885290e-02,  7.06331804e-03,  3.31770219e-02,
          4.86553945e-02, -1.53257139e-02, -1.48317590e-02,
          3.89952995e-02, -2.15779990e-04,  3.00152414e-02,
          1.65792592e-02],
        [-1.40450597e-02,  2.05293931e-02,  1.96136124e-02,
         -2.96669733e-02,  4.83083017e-02, -1.54336095e-02,
          3.45417745e-02, -1.62711367e-02,  4.482072

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 8140, 4354, 3318,  372], dtype=int32)

In [18]:
# Reshape your input data to have an explicit batch dimension
# We are assuming embedded_docs[0] represents a single sample
# The new shape will be (1, sent_length)
reshaped_input = embedded_docs[0].reshape(1, -1)

# Now make the prediction
# predictions =
model.predict(reshaped_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[-0.02568853,  0.00706332,  0.03317702,  0.04865539,
         -0.01532571, -0.01483176,  0.0389953 , -0.00021578,
          0.03001524,  0.01657926],
        [-0.02568853,  0.00706332,  0.03317702,  0.04865539,
         -0.01532571, -0.01483176,  0.0389953 , -0.00021578,
          0.03001524,  0.01657926],
        [-0.02568853,  0.00706332,  0.03317702,  0.04865539,
         -0.01532571, -0.01483176,  0.0389953 , -0.00021578,
          0.03001524,  0.01657926],
        [-0.02568853,  0.00706332,  0.03317702,  0.04865539,
         -0.01532571, -0.01483176,  0.0389953 , -0.00021578,
          0.03001524,  0.01657926],
        [-0.01404506,  0.02052939,  0.01961361, -0.02966697,
          0.0483083 , -0.01543361,  0.03454177, -0.01627114,
          0.04482073, -0.01414611],
        [ 0.01881042,  0.00152659, -0.01630528,  0.03758207,
          0.01132361, -0.00680513,  0.02860479,  0.03219101,
          0.00257663, -0.00411155],
        [-0.01234936,  0.00185442, -0.01976795,  0.0